language: node_js
node_js:
- '6'

before_install:
  - stty cols 80

dist: trusty
sudo: required
addons:
  firefox: stable
  chrome: stable

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- npm install -g concurrently@3.1.0
script:
- npm run build_vue_dev
- npm run build_vue_prod
- karma start --single-run
- http-server --silent &
- testcafe chrome testCafe/ --reporter minimal
#- npm run testcafe_sauce
- if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then echo "Starting functional tests on SauceLabs..."; npm run testcafe_sauce; fi
before_deploy: tar -zcvf surveyjs.tar.gz packages
deploy:
- provider: script
  script: chmod +x ./deploy_npm.sh && ./deploy_npm.sh
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    recipients:
      - nasir.ghaznavi@outlook.com
